#ifndef AD_CONSTANTS_H
#define AD_CONSTANTS_H

#define LONGITUDINAL_DIFFERENCE_PERCENTAGE 0.05f

#define EGO_VEHICLE_ID (-1)
#define NUM_VEHICLES_ON_LANE (2)

#define NUM_CYCLES (1000)
#define NUM_VEHICLES (6)

#endif // AD_CONSTANTS_H
