
#ifndef AD_TYPES_H
#define AD_TYPES_H

enum LaneAssociationType
{
    LANE_ASSOCIATION_TYPE_NONE = 0,
    LANE_ASSOCIATION_TYPE_RIGHT = 1,
    LANE_ASSOCIATION_TYPE_CENTER = 2,
    LANE_ASSOCIATION_TYPE_LEFT = 3
};

#endif // AD_TYPES_H
